### ISSUE TITLE
Quickstart Guide Ionic is not starting PSPDFKit

### ISSUE THREAD

**Issue by stetro** [PSPDFKit/Cordova-Android#52]
I followed the described instructions with the following steps:
1. Project setup with these commands:
```
ionic start todo blank --type ionic1
cd todo
ionic cordova platform add android@8.0.0
ionic cordova plugin add https://github.com/PSPDFKit/Cordova-Android.git
cp ../local.properties platforms/android/
```
2. add PSPDFKit command inside `$ionicPlatform.ready`
```
PSPDFKit.showDocumentFromAssets("www/documents/Document.pdf", {
    title: "My PDF Document",
    scrollDirection: PSPDFKit.PageScrollDirection.VERTICAL,
    scrollMode: PSPDFKit.ScrollMode.CONTINUOUS,
    useImmersiveMode: true
});
```
3. add demo pdf file
``` 
mkdir www/documents
cp ../Document.pdf www/documents/
```
4. `ionic cordova run android`

Build succeeds but when starting my application the PSPDFKit plugin call leads to the following exception:
```
07-08 14:25:07.573 25204 25204 D SystemWebChromeClient: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js: Line 52 : subscriber listener for onDocumentSaved
07-08 14:25:07.573 25204 25204 I chromium: [INFO:CONSOLE(52)] "subscriber listener for onDocumentSaved", source: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js (52)
07-08 14:25:07.574 25204 25204 D SystemWebChromeClient: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js: Line 52 : subscriber listener for onDocumentSaveFailed
07-08 14:25:07.574 25204 25204 I chromium: [INFO:CONSOLE(52)] "subscriber listener for onDocumentSaveFailed", source: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js (52)
07-08 14:25:07.574 25204 25204 D SystemWebChromeClient: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js: Line 52 : subscriber listener for onDocumentDismissed
07-08 14:25:07.575 25204 25204 I chromium: [INFO:CONSOLE(52)] "subscriber listener for onDocumentDismissed", source: http://localhost/plugins/pspdfkit-cordova-android/www/PSPDFKit.js (52)
07-08 14:25:07.590 25204 25319 I App     : WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
07-08 14:08:15.796 22939 23097 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String, java.lang.String)' on a null object ref
erence                                                                
07-08 14:08:15.796 22939 23097 W System.err:    at com.pspdfkit.cordova.PSPDFKitCordovaPlugin.initializePSPDFKit(PSPDFKitCordovaPlugin.java:94)
07-08 14:08:15.796 22939 23097 W System.err:    at com.pspdfkit.cordova.PSPDFKitCordovaPlugin.initialize(PSPDFKitCordovaPlugin.java:62)                                                                              
07-08 14:08:15.796 22939 23097 W System.err:    at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
07-08 14:08:15.796 22939 23097 W System.err:    at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)                                                                                                
07-08 14:08:15.796 22939 23097 W System.err:    at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
07-08 14:08:15.796 22939 23097 W System.err:    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)                                                                      
07-08 14:08:15.796 22939 23097 W System.err:    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
07-08 14:08:15.796 22939 23097 W System.err:    at android.os.MessageQueue.nativePollOnce(Native Method)        
07-08 14:08:15.796 22939 23097 W System.err:    at android.os.MessageQueue.next(MessageQueue.java:336)      
07-08 14:08:15.796 22939 23097 W System.err:    at android.os.Looper.loop(Looper.java:174)                  
07-08 14:08:15.796 22939 23097 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:67)  

```

This problem occurs on all my available devices (Pixel 3a, Pixel C)
```
node lts/dubnium
ionic -v 5.2.1
cordova -v 9.0.0
android build sdk 8.1 (27)  - also tested on 9.0 (29)
PSPDFKit Test License
```

Looks like the application Infos metadata is nullable in `PSPDFKitCordovaPlugin.java:93`

**Comment by davidschreiber** [comment]
Hi @stetro 👋 Thanks for reaching out to us. Could you please send us your support request once more via our technical support platform at https://pspdfkit.com/support/request/ and I'll make sure someone picks up your case right away. The GitHub issue tracker is primarily used for feature requests/enhancements. Thanks a lot!
